/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import src.Analise;
import src.Escrita;

/**
 *
 * @author bruno
 */
public class TelaPrincipal extends javax.swing.JFrame {
    public static String newPath;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritaContratos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        campoPath = new javax.swing.JTextField();
        selecionarArquivo = new javax.swing.JButton();
        transformarContrato = new javax.swing.JButton();
        botaoAgora = new javax.swing.JRadioButton();
        botaoSol = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Automato do Contrato:");

        selecionarArquivo.setText("Abrir Arquivo");
        selecionarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarArquivoActionPerformed(evt);
            }
        });

        transformarContrato.setText("Transformar em Contrato Inteligente");
        transformarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformarContratoActionPerformed(evt);
            }
        });

        escritaContratos.add(botaoAgora);
        botaoAgora.setText("Escrever funções agora");
        botaoAgora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAgoraActionPerformed(evt);
            }
        });

        escritaContratos.add(botaoSol);
        botaoSol.setText("Escrever funções no .sol");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(transformarContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoPath, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecionarArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoSol)
                                    .addComponent(botaoAgora))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecionarArquivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoAgora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSol)
                .addGap(6, 6, 6)
                .addComponent(transformarContrato)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selecionarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarArquivoActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            campoPath.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_selecionarArquivoActionPerformed

    private void transformarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformarContratoActionPerformed
        Analise analise = new Analise();
        try {
            analise.iniciarAnalise(campoPath.getText());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Arquivo Inválido.", "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Escrita escrita = new Escrita();
        newPath = campoPath.getText().replace(".txt", ".sol");
        try {
            if(escritaContratos.getSelection()==null){
                JOptionPane.showMessageDialog(null, "Escolha uma das opções de escrita.", "Erro", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (escritaContratos.getSelection().equals(botaoSol.getModel())) {
                Escrita.op = 0;
                escrita.EscreverContrato(newPath);
                JOptionPane.showMessageDialog(null, "Contrato Traduzido com Sucesso.");
            }else if((escritaContratos.getSelection().equals(botaoAgora.getModel()))){
                Escrita.op = 1;
                TelaEscritaFuncoes tela_escrita = new TelaEscritaFuncoes();
                tela_escrita.setVisible(true);
            }

        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_transformarContratoActionPerformed

    private void botaoAgoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAgoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAgoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botaoAgora;
    private javax.swing.JRadioButton botaoSol;
    private javax.swing.JTextField campoPath;
    private javax.swing.ButtonGroup escritaContratos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton selecionarArquivo;
    private javax.swing.JButton transformarContrato;
    // End of variables declaration//GEN-END:variables
}
